### ISSUE TITLE
Crash on start: "Image could not be created"

### ISSUE THREAD

**Issue by Deuchnord** [squalou/google-chat-linux#16] opened 2020-06-22 14:15 UTC
Since the v0.5.0 update, the app crashes on startup with the following message:
![Uncaught Exception: Error: Image could not be created from /opt/google-chat-linux/resources/app.asar/-/assets/icon/icon.png](https://user-images.githubusercontent.com/7600265/85297024-82c6f500-b4a2-11ea-90fd-05424d07940d.png)

OS: Arch Linux
Updated from 0.4.5 from the AUR (the Electron 8 version, not tested with the Electron 7 version).

**Comment by squalou** [comment] 2020-06-22 15:55
Hi,
indeed ... other friends reported it. Yet I cannot reproduce it on my own computer.

Very weird.

The only change since previous version is the electron version.
It's maybe related to the packaging ?

Could you try to start it from sources ? (explained in README)

**Comment by squalou** [comment] 2020-06-22 18:12
update
reproduced on an ubuntu 18.04 I have somewhere.

Works from source (running 'google-chat-linux.sh') but not from .deb

Really looks like a packaging issue.

<tl/dr>
why the hell do I always end up try ing to maintain and fix technos I despise. Must be bad karma :)
</tl/dr>

**Comment by alescdb** [comment] 2020-06-22 19:09
Same issue here, works with google-chat-linux.sh but not in release (`npm run pack`).
I've looked around and maybe found a solution :+1: 
```
  "build": {
    "asar": false
  }
```
It seems too "work" but afer that we are missing some assets.
I'm not familar (at all) with electron so I'm not sure it is a good solution.

**Comment by squalou** [comment] 2020-06-22 20:12
should be fixed but after .deb is generated ... it s not.

**Closed** 2020-06-22 20:14 UTC

**Comment by squalou** [comment] 2020-06-22 20:33
For the records,
the 'extraResources' in package.json behaved previously as a list of thing to include.
Now, its the other way around : resources listed in extraResources array seem to *not* be included in asar package.

Removing extraResources entirely ... includes entire 'assets' directory.

**Comment by alescdb** [comment] 2020-06-23 07:02
Now the tray appear as Google "G" (at least on Gnome) :

![image](https://user-images.githubusercontent.com/5646825/85371141-14307880-b530-11ea-831d-83fff6dea371.png)
