### ISSUE TITLE
Google breaks out

### ISSUE THREAD

**Issue by druuhl** [squalou/google-chat-linux#40] opened 2021-09-07 10:05 UTC
After an issue with auth today, auth was still delegated to my standardbrowser AND everytime i hit the "Main Menu/Chat/Chatrooms/Meet" expand Button, a browser windows opens and i land on

 - https://www.google.com/intl/de/gmail/about/
 
because im not authenticated in this browser, means google wants to open googlechat/meet/... Urls in Browser

**Comment by squalou** [comment] 2021-09-08 07:30
To fix this, I will need your help to track down the numerous redirections that are done unederneath.

If you have a few minutes available, you'll need to
- hit Alt in google chat linux
- choose "DevTools"
- choose "Network" tab

![image](https://user-images.githubusercontent.com/4623644/132465114-bcde215b-082d-4f17-bc1f-ced9a6c0209a.png)


Then, also try to do the same thing in your browser, prepare it so that redirected urls can be tracked there.

Then, reproduce the login issue you have

In the Network page, succession of urls will be displayed (among many other things...)


This way I'll see which ones should be forcibly kept inside chat client.


I hope you'll manage to get the info, would be very helpful.

**Comment by druuhl** [comment] 2021-09-08 08:00
Thank you, untick "open urls in external browser"  solved my problem.

regards
Stefan

**Comment by squalou** [comment] 2021-09-08 09:13
Good news!

Bad news is : it will probably happen again next time you'll have to login, probably next month (Google tends to force re-auth once a month)

if you ever find some spare time when it happens, I'd still be interested in the Devtools / Network operation, and a screenshot at the end. Would be nice to fix it once and for all.

(but don't worry if you don't feel like doing it :) )


Closing the issue in the meantime.

**Comment by squalou** [comment] 2021-09-09 12:52
Good (?) news I was able to  face the same issue.
I'll probably be able to fix it.

**Comment by vlovich** [comment] 2021-09-17 14:17
I have the same problem as @druuhl. I set the preference to "open urls in external browser" because I personally found the built-in browser to not be a great experience. However, this seems to have applied to URLs that are needed for sign-in breaking sign-in flow. I'm not sure how to work around this since that preference only seems accessible via the UI after sign-in (not even via the tray)... Time to go hunting for it on-disk...

**Comment by vlovich** [comment] 2021-09-17 14:19
`$HOME/.config/google-hangouts-chat-linux.json`

**Comment by squalou** [comment] 2021-09-17 16:35
Hi,
indeed, you're analysis is perfectly right.
When ticking "open urls in external browser" (which I recommend too), there is a filter applied that is suposed to keep "login" related  urls inside.
BUT, google tends to move things around A LOT

It's a bit hard to reproduce, it occurs once every month. Next time I'll be faced with this, I'll open 'dev tools' and check 'network' panel to try to follow all redirections and figure out how to trap them.

**Comment by squalou** [comment] 2022-02-16 07:58
Still no definitive fix, but a hint.

When login breaks out to browser : Quit  (Ctrl Q) chat app.
Relaunch
It still breaks out to browser
Quit again (Ctrl Q)
Relaunch

And this time it should stay inside the app.

(no idea why, at least it works like this for me)

**Comment by vwbusguy** [comment] 2022-04-21 16:52
Updating the urlNotRedirected seems to have fixed this for me.  I submitted a PR for it.

**Closed** 2022-04-22 08:54 UTC
